### ISSUE TITLE
the calculation of the uncertainty

### ISSUE THREAD

**Issue by 141forever** [IML-DKFZ/values#1]
Hello! Congratulate on your excellent work!
I am new to the area of uncertainty estimation, I am now wondering if there is some example of equation 1 in the paper. It may help me understand.

**Comment by kck278** [comment]
Hello,
Thanks! Sure, if you want to know how this formula is implemented, you can check out the  [calculate_uncertainty function in uncertainty_modeling/test_3D.py](https://github.com/IML-DKFZ/values/blob/53b25c8eb176e614cc99bd06fa62c679611ed0ce/uncertainty_modeling/test_3D.py#L486)

**Comment by 141forever** [comment]
GREAT! I will check it out!
